### PR TITLE
GDPHAR-3320 - Created remove_dotnet_agent recipe and testing

### PR DESCRIPTION
**Pull request by f1yers**

### CODE REVIEW

**Comment by f1yers** [comment]
test this please

**Comment by ronlipke** [comment]
test this please

**Comment by ronlipke** [comment]
test this please

**Comment by f1yers** [comment]
test this please

**Comment by akemner** [comment]
test this please

**Comment by ronlipke** [comment]
test this please

**Comment by ronlipke** [comment]
test this please

**Pull request merged**
